### ISSUE TITLE
Afreeca Support

### ISSUE THREAD

**Issue by dimmui** [ILiedAboutCake/Rustla2#11]
Hello developers,

I would like to make a case for adding Afreeca support to Overrustle with the next update. Afreeca is the premiere website for Starcraft: Brood War streamers and over the past year the Afreeca Starleague events have been gaining momentum by getting many viewers on Overrustle via Twitch. This content is great, but fans of Brood War cannot watch streamers such as Flash, Jaedong, Nada, Bisu, Shuttle, Larva, and more while shitposting in d.gg chat without Afreeca support.

Thank you for listening.
Love, Dimmui

**Comment by blushies** [comment]
Afreeca stream urls require two parts which are separated by a `/`, `lion6150` and `189134874` in this example: `http://play.afreecatv.com/lion6150/189134874/embed`. Worked around this by having the router take everything after the second `/` in the url and make that into a `channel` param.

So to go to an afreeca stream you would go to something like `http://domain.com/afreeca/lion6150/189134874`
