### ISSUE TITLE
`state.stream` not set to `null` when navigating to homepage

### ISSUE THREAD

**Issue by KenanY** [ILiedAboutCake/Rustla2#23]
Steps to reproduce:

  1. Open homepage. `state.stream` is `null` at this point.
  2. Navigate to a stream via the header form. `state.stream` is set to the stream's ID.
  3. Click the "OverRustle" homepage link at the top left. `state.stream` is not reset to `null`, but it should be since user is no longer watching a stream.

**Comment by blushies** [comment]
good catch
