### ISSUE TITLE
Error when trying to sign in for beta.overrustle

### ISSUE THREAD

**Issue by Loomies** [ILiedAboutCake/Rustla2#24]
This is the error

"{"error":"Internal Server Error","message":"redirect_mismatch","status":500}"

**Comment by KenanY** [comment]
Assigning to @ILiedAboutCake to verify that the `TWITCH_REDIRECT_URI` env var matches the Redirect URI defined in the Twitch app (like in [here](https://github.com/ILiedAboutCake/Rustla2#creating-twitch-client)).

**Comment by ILiedAboutCake** [comment]
config needed https:// to match https:// on Twitch. Login's should be working now.
