### ISSUE TITLE
Allow Advanced embeds to not use HTTPS

### ISSUE THREAD

**Issue by PurpleCox** [ILiedAboutCake/Rustla2#8]
I used to watch BBC news on overrustle but I can't now because the embed is not HTTPS. I would guess many other sites cannot be embedded on advanced anymore because of it.

**Comment by blushies** [comment]
Not sure how/if this is possible now that @ILiedAboutCake enabled forced https

**Comment by PurpleCox** [comment]
Oh sorry, forgot to delete this. I already talked with dashh and decided to suck it up and just allow it to load unsafe scripts each time 👌
